### PR TITLE
feat(core): Add zsh plugin

### PR DESCRIPTION
**Pull request by coolapso**
Following the discussion at: https://github.com/ohmyzsh/ohmyzsh/pull/12452

If you consider that it's worth I'll open up the pull request to oh-my-zsh wiki ... but at this point not sire if its worth, believe here is the most relevant place to have it and then when the stargazers are enough can reach out and try to include it on oh-my-zsh as well.

### CODE REVIEW

**Comment by kvendingoldo** [comment]
@coolapso I think that we can try to open PR to wiki repository. Thank you very much for your efforts!

**Review by kvendingoldo — APPROVED** [review]
LGTM

**Comment by coolapso** [comment]
> @coolapso I think that we can try to open PR to wiki repository. Thank you very much for your efforts!

Will do that then.

**Comment by coolapso** [comment]
here: https://github.com/ohmyzsh/wiki/pull/56

**Pull request merged**
